/*
 * JuvenileAttributesCustomizer.java
 *
 * 20210206: 1. Created class from LarvalAttributesCustomizer to handle attributes for juvenile stages.
 */

package sh.pcod;

import wts.models.DisMELS.framework.*;
import wts.models.DisMELS.gui.AttributesCustomizer;

/**
 * @author William Stockhausen
 */
public class JuvenileAttributesCustomizer extends AttributesCustomizer {

    private boolean showHorizPos = true;
    private boolean showVertPos = true;
    
    private AbstractJuvenileAttributes attributes = null;
    
    /**
     * Creates new customizer NonEggStageAttributesCustomizer
     */
    public JuvenileAttributesCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        czrStandardAttributes = new wts.models.DisMELS.gui.AbstractLHSAttributesCustomizer();
        jPanel2 = new javax.swing.JPanel();
        jchkAttached = new javax.swing.JCheckBox();
        jtfSL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfTL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDW = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfWW = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(czrStandardAttributes, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional attributes"));

        jchkAttached.setText("attached?");
        jchkAttached.setActionCommand("");
        jchkAttached.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchkAttachedItemStateChanged(evt);
            }
        });

        jtfSL.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfSL.setText("0");
        jtfSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSLActionPerformed(evt);
            }
        });

        jLabel2.setText("standard length (mm)");
        jLabel2.setToolTipText("diameter in mm");

        jtfTL.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfTL.setText("0");
        jtfTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTLActionPerformed(evt);
            }
        });

        jLabel3.setText("total length (mm)");
        jLabel3.setToolTipText("diameter in mm");

        jtfDW.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfDW.setText("0");
        jtfDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDWActionPerformed(evt);
            }
        });

        jLabel4.setText("dry weight (micrograms)");
        jLabel4.setToolTipText("diameter in mm");

        jtfWW.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfWW.setText("0");
        jtfWW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWWActionPerformed(evt);
            }
        });

        jLabel5.setText("wet weight (micrograms)");
        jLabel5.setToolTipText("diameter in mm");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jchkAttached)
                .add(0, 0, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfSL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfTL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfWW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfDW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jchkAttached)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfSL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfTL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfDW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfWW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSLActionPerformed
        Double n = new Double(jtfSL.getText());
        attributes.setValue(attributes.PROP_SL,n);
    }//GEN-LAST:event_jtfSLActionPerformed

    private void jchkAttachedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchkAttachedItemStateChanged
        attributes.setValue(attributes.PROP_attached, jchkAttached.isSelected());
    }//GEN-LAST:event_jchkAttachedItemStateChanged

    private void jtfTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTLActionPerformed
        Double n = new Double(jtfTL.getText());
        attributes.setValue(attributes.PROP_TL,n);
    }//GEN-LAST:event_jtfTLActionPerformed

    private void jtfDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDWActionPerformed
        Double n = new Double(jtfDW.getText());
        attributes.setValue(attributes.PROP_DW,n);
    }//GEN-LAST:event_jtfDWActionPerformed

    private void jtfWWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWWActionPerformed
        Double n = new Double(jtfWW.getText());
        attributes.setValue(attributes.PROP_WW,n);
    }//GEN-LAST:event_jtfWWActionPerformed

    @Override
    public void setObject(Object bean) {
        if (bean instanceof AbstractLarvalAttributes) {
            setAttributes((AbstractLarvalAttributes) bean);
        }
    }
    
    @Override
    public AbstractLarvalAttributes getAttributes() {
        return attributes;
    }
    
    @Override
    public void setAttributes(LifeStageAttributesInterface newAtts) {
        if (newAtts instanceof AbstractJuvenileAttributes) {
            attributes = (AbstractJuvenileAttributes) newAtts;
            czrStandardAttributes.setObject(attributes);
            Double d = null;
            jchkAttached.setSelected(attributes.getValue(attributes.PROP_attached,true));
            jtfSL.setText(attributes.getValue(attributes.PROP_SL,d).toString());
        }
    }
    
    @Override
    public void showHorizPos(boolean b) {
        czrStandardAttributes.showHorizPos(b);
        revalidate();
    }
    
    @Override
    public void showVertPos(boolean b) {
        czrStandardAttributes.showVertPos(b);
        revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wts.models.DisMELS.gui.AbstractLHSAttributesCustomizer czrStandardAttributes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jchkAttached;
    private javax.swing.JTextField jtfDW;
    private javax.swing.JTextField jtfSL;
    private javax.swing.JTextField jtfTL;
    private javax.swing.JTextField jtfWW;
    // End of variables declaration//GEN-END:variables
    
}
